#!/usr/bin/env python

import os
import sys
import json
import prettytable

dps = os.popen('docker ps -q').read()

lines = dps.split('\n')


if len(lines) < 2:
    print 'no containers running'
    sys.exit(0)

def flattenports(a):
    r = ""
    for con, host in a.items():
        if r:
            r += ","
        r += 'c/' + con
        if host:
            r += '->h/' + host[0]['HostPort']
    return r

t = prettytable.PrettyTable(
   header = False, border = False
)
t.align = 'l'
t.left_padding_width = 0

for cid in lines[1:]:
    if not cid:
        continue
    d = json.loads(os.popen('docker inspect ' + cid).read())

    ip = d[0]['NetworkSettings']['IPAddress']
    name = d[0]['Name']
    p = flattenports(d[0]['NetworkSettings']['Ports'])
    t.add_row([cid, ip, name, p])

print t
